services:
  - type: web
    name: ovt-converter
    runtime: docker
    rootDir: converter
    plan: free
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://felipescandian.github.io
